name: 功能 / Enhancement
description:  "提议新功能，或改善已有功能 / New feature request or improvement suggestion"
labels: [enhancement]
body:
- type: textarea
  id: description
  attributes:
    label: 描述 / Description
    placeholder: |
      是否可以考虑...
      I suggest ...
  validations:
    required: true
